/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminPeopleRouteImport } from './routes/admin.people'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentHistoryRouteImport } from './routes/parent.history'
import { Route as ParentNotificationsRouteImport } from './routes/parent.notifications'
import { Route as DriverTripTripIdRouteImport } from './routes/driver.trip.$tripId'
import { Route as ParentTrackChildIdRouteImport } from './routes/parent.track.$childId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/admin/fleet',
  path: '/admin/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/admin/people',
  path: '/admin/people',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentHistoryRoute = ParentHistoryRouteImport.update({
  id: '/parent/history',
  path: '/parent/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/parent/notifications',
  path: '/parent/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripTripIdRoute = DriverTripTripIdRouteImport.update({
  id: '/driver/trip/$tripId',
  path: '/driver/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTrackChildIdRoute = ParentTrackChildIdRouteImport.update({
  id: '/parent/track/$childId',
  path: '/parent/track/$childId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/people': typeof AdminPeopleRoute
  '/parent/history': typeof ParentHistoryRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/driver/trip/$tripId': typeof DriverTripTripIdRoute
  '/parent/track/$childId': typeof ParentTrackChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/people': typeof AdminPeopleRoute
  '/parent/history': typeof ParentHistoryRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/parent': typeof ParentIndexRoute
  '/driver/trip/$tripId': typeof DriverTripTripIdRoute
  '/parent/track/$childId': typeof ParentTrackChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/people': typeof AdminPeopleRoute
  '/parent/history': typeof ParentHistoryRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/driver/trip/$tripId': typeof DriverTripTripIdRoute
  '/parent/track/$childId': typeof ParentTrackChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/fleet'
    | '/admin/people'
    | '/parent/history'
    | '/parent/notifications'
    | '/admin/'
    | '/driver/'
    | '/parent/'
    | '/driver/trip/$tripId'
    | '/parent/track/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/fleet'
    | '/admin/people'
    | '/parent/history'
    | '/parent/notifications'
    | '/admin'
    | '/driver'
    | '/parent'
    | '/driver/trip/$tripId'
    | '/parent/track/$childId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/fleet'
    | '/admin/people'
    | '/parent/history'
    | '/parent/notifications'
    | '/admin/'
    | '/driver/'
    | '/parent/'
    | '/driver/trip/$tripId'
    | '/parent/track/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  ParentHistoryRoute: typeof ParentHistoryRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  ParentIndexRoute: typeof ParentIndexRoute
  DriverTripTripIdRoute: typeof DriverTripTripIdRoute
  ParentTrackChildIdRoute: typeof ParentTrackChildIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/admin/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/history': {
      id: '/parent/history'
      path: '/parent/history'
      fullPath: '/parent/history'
      preLoaderRoute: typeof ParentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/parent/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trip/$tripId': {
      id: '/driver/trip/$tripId'
      path: '/driver/trip/$tripId'
      fullPath: '/driver/trip/$tripId'
      preLoaderRoute: typeof DriverTripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/track/$childId': {
      id: '/parent/track/$childId'
      path: '/parent/track/$childId'
      fullPath: '/parent/track/$childId'
      preLoaderRoute: typeof ParentTrackChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  ParentHistoryRoute: ParentHistoryRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  ParentIndexRoute: ParentIndexRoute,
  DriverTripTripIdRoute: DriverTripTripIdRoute,
  ParentTrackChildIdRoute: ParentTrackChildIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
